/**
 * Fast catalog expansion — add books only, no English-title conversion.
 * Resumes from existing mockBooksGenerated.ts until TARGET_COUNT.
 *
 * Usage: node scripts/addBooksFast.mjs
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TARGET_COUNT = 40000;
const PAGE_SIZE = 100;
const USER_AGENT = "LeafLibrary/1.0 (fast catalog expand)";

const SUBJECT_QUERIES = [
  "subject:fantasy",
  "subject:science_fiction",
  "subject:mystery",
  "subject:thriller",
  "subject:romance",
  "subject:historical_fiction",
  "subject:biography",
  "subject:young_adult",
  "subject:horror",
  "subject:adventure",
  "subject:classics",
  "subject:literary",
  "subject:crime",
  "subject:suspense",
  "subject:contemporary",
  "subject:memoir",
  "subject:poetry",
  "subject:philosophy",
  "subject:psychology",
  "subject:business",
  "subject:history",
  "subject:science",
  "subject:dystopia",
  "subject:space_opera",
  "subject:urban_fantasy",
  "subject:detective",
  "subject:short_stories",
  "subject:essays",
  "language:eng",
];

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

function pickIsbn13(isbnList = []) {
  const cleaned = isbnList.map((i) => String(i).replace(/[^0-9Xx]/g, ""));
  return cleaned.find((c) => /^978\d{10}$/.test(c) && !/^97810[0-3]/.test(c)) || null;
}

function isFakeIsbn(isbn) {
  return !/^978\d{10}$/.test(isbn) || /^97810[0-3]/.test(isbn);
}

function stableRating(title) {
  let hash = 0;
  for (let i = 0; i < title.length; i++) hash += title.charCodeAt(i);
  return parseFloat((3.7 + (hash % 13) / 10).toFixed(1));
}

function loadCatalog() {
  const outPath = path.resolve(__dirname, "../../frontend/src/data/mockBooksGenerated.ts");
  const raw = fs.readFileSync(outPath, "utf8");
  const match = raw.match(/export const GENERATED_BOOKS[\s\S]*?=\s*(\[)/);
  const start = match.index + match[0].length - 1;
  const end = raw.lastIndexOf("]");
  return JSON.parse(raw.slice(start, end + 1));
}

function loadCoverMap() {
  const map = {};
  try {
    const raw = fs.readFileSync(
      path.resolve(__dirname, "../../frontend/src/data/coverOverrides.ts"),
      "utf8"
    );
    for (const m of raw.matchAll(/"(\d{13})":\s*(\d+)/g)) map[m[1]] = Number(m[2]);
  } catch {
    // empty
  }
  return map;
}

function writeCatalog(books, coverMap) {
  const exact = books.slice(0, TARGET_COUNT);
  const outPath = path.resolve(__dirname, "../../frontend/src/data/mockBooksGenerated.ts");
  fs.writeFileSync(
    outPath,
    `// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.\n` +
      `// Real editions (ISBN-13 + cover). Generated ${new Date().toISOString()}\n` +
      `import { Book } from "./mockData";\n\n` +
      `export const GENERATED_BOOKS: Book[] = ${JSON.stringify(exact, null, 2)};\n`,
    "utf8"
  );
  const ids = new Set(exact.map((b) => b.id));
  const entries = Object.entries(coverMap)
    .filter(([isbn]) => ids.has(isbn))
    .sort(([a], [b]) => a.localeCompare(b));
  fs.writeFileSync(
    path.resolve(__dirname, "../../frontend/src/data/coverOverrides.ts"),
    `// Auto-generated Open Library cover IDs (isbn -> cover_i)\n` +
      `// Generated ${new Date().toISOString()} — real catalog only\n` +
      `export const COVER_ID_BY_ISBN: Record<string, number> = {\n` +
      entries.map(([isbn, id]) => `  "${isbn}": ${id},`).join("\n") +
      `\n};\n`,
    "utf8"
  );
  console.log(`\nCheckpoint wrote ${exact.length} books, ${entries.length} covers`);
}

async function fetchJson(url, timeoutMs = 12000) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, {
      signal: controller.signal,
      headers: { "User-Agent": USER_AGENT, Accept: "application/json" },
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return res.json();
  } finally {
    clearTimeout(timer);
  }
}

function pushDoc(doc, books, seen, coverMap, genre) {
  if (!doc.cover_i || !doc.title || !doc.author_name?.length) return false;
  const isbn = pickIsbn13(doc.isbn || []);
  if (!isbn || isFakeIsbn(isbn) || seen.has(isbn)) return false;
  seen.add(isbn);
  coverMap[isbn] = doc.cover_i;
  const title = String(doc.title).trim();
  const author = doc.author_name[0];
  const year = doc.first_publish_year || 2000;
  books.push({
    id: isbn,
    title,
    author,
    year,
    description: `${title} by ${author}` + (year ? `, first published ${year}.` : "."),
    coverImage: `https://covers.openlibrary.org/b/id/${doc.cover_i}-L.jpg?default=false`,
    averageRating:
      typeof doc.ratings_average === "number"
        ? parseFloat(Math.min(4.9, Math.max(3.5, doc.ratings_average)).toFixed(1))
        : stableRating(title),
    genres: [genre, "Popular"].slice(0, 4),
    pages: doc.number_of_pages_median || 300,
  });
  return true;
}

async function crawlOl(q, genre, books, seen, coverMap) {
  let page = 1;
  let empty = 0;
  while (books.length < TARGET_COUNT && page <= 80 && empty < 3) {
    const url =
      `https://openlibrary.org/search.json?q=${encodeURIComponent(q)}` +
      `&language=eng&limit=${PAGE_SIZE}&page=${page}` +
      `&fields=key,title,author_name,first_publish_year,number_of_pages_median,isbn,cover_i,subject,ratings_average`;
    process.stdout.write(`\r[${books.length}/${TARGET_COUNT}] ${genre} p${page}…`);
    try {
      const data = await fetchJson(url);
      const docs = data.docs || [];
      if (!docs.length) break;
      let added = 0;
      for (const doc of docs) {
        if (books.length >= TARGET_COUNT) break;
        if (pushDoc(doc, books, seen, coverMap, genre)) added++;
      }
      if (added === 0) empty++;
      else empty = 0;
    } catch (err) {
      console.warn(`\nOL warn: ${err.message}`);
      empty++;
      await sleep(1200);
    }
    page++;
    await sleep(200);
  }
}

async function crawlWikidata(books, seen, coverMap) {
  let offset = 0;
  while (books.length < TARGET_COUNT && offset < 25000) {
    const query = `
      SELECT DISTINCT ?isbn ?title ?authorLabel ?year WHERE {
        ?book wdt:P31/wdt:P279* wd:Q7725634 .
        ?book wdt:P212 ?isbn .
        ?book rdfs:label ?title .
        FILTER(LANG(?title) = "en")
        FILTER(STRSTARTS(?isbn, "978"))
        OPTIONAL { ?book wdt:P50 ?author . }
        OPTIONAL { ?book wdt:P577 ?date . BIND(YEAR(?date) AS ?year) }
        SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
      }
      LIMIT 500 OFFSET ${offset}
    `;
    process.stdout.write(`\r[${books.length}/${TARGET_COUNT}] wikidata @${offset}…`);
    try {
      const data = await fetchJson(
        "https://query.wikidata.org/sparql?format=json&query=" + encodeURIComponent(query),
        45000
      );
      const rows = data?.results?.bindings || [];
      if (!rows.length) break;
      let added = 0;
      for (const row of rows) {
        if (books.length >= TARGET_COUNT) break;
        const isbn = String(row.isbn?.value || "").replace(/[^0-9]/g, "");
        if (isFakeIsbn(isbn) || seen.has(isbn)) continue;
        const title = String(row.title?.value || "").trim();
        if (!title) continue;
        const author = String(row.authorLabel?.value || "Unknown Author").trim();
        if (!author || author.startsWith("Q")) continue;
        const year = row.year?.value ? Number(row.year.value) : 2000;
        seen.add(isbn);
        books.push({
          id: isbn,
          title,
          author,
          year: Number.isFinite(year) ? year : 2000,
          description: `${title} by ${author}.`,
          coverImage: `https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg?default=false`,
          averageRating: stableRating(title),
          genres: ["Literary Fiction", "Popular"],
          pages: 300,
        });
        added++;
      }
      if (added === 0 && rows.length < 500) break;
    } catch (err) {
      console.warn(`\nWikidata warn: ${err.message}`);
      await sleep(1500);
    }
    offset += 500;
    if (offset % 2000 === 0) writeCatalog(books, coverMap);
    await sleep(400);
  }
}

async function main() {
  const coverMap = loadCoverMap();
  const books = loadCatalog();
  const seen = new Set(books.map((b) => b.id));
  console.log(`Start ${books.length}, target ${TARGET_COUNT}, need ${TARGET_COUNT - books.length}`);

  // Prefer Open Library when reachable
  let olOk = false;
  try {
    await fetchJson("https://openlibrary.org/search.json?q=test&limit=1", 8000);
    olOk = true;
  } catch {
    console.log("Open Library unreachable — using Wikidata");
  }

  if (olOk) {
    for (const q of SUBJECT_QUERIES) {
      if (books.length >= TARGET_COUNT) break;
      const before = books.length;
      const genre = q.includes("fantasy")
        ? "Fantasy"
        : q.includes("science")
          ? "Sci-Fi"
          : q.includes("mystery") || q.includes("thriller") || q.includes("crime")
            ? "Mystery & Thriller"
            : q.includes("romance")
              ? "Romance"
              : "Literary Fiction";
      await crawlOl(q, genre, books, seen, coverMap);
      if (books.length > before) writeCatalog(books, coverMap);
    }
  }

  if (books.length < TARGET_COUNT) {
    await crawlWikidata(books, seen, coverMap);
  }

  // Editions sort fill
  if (olOk && books.length < TARGET_COUNT) {
    let page = 1;
    while (books.length < TARGET_COUNT && page <= 200) {
      process.stdout.write(`\r[${books.length}/${TARGET_COUNT}] editions p${page}…`);
      try {
        const data = await fetchJson(
          `https://openlibrary.org/search.json?q=*&language=eng&sort=editions&limit=${PAGE_SIZE}&page=${page}` +
            `&fields=key,title,author_name,first_publish_year,number_of_pages_median,isbn,cover_i,ratings_average`
        );
        for (const doc of data.docs || []) {
          if (books.length >= TARGET_COUNT) break;
          pushDoc(doc, books, seen, coverMap, "Literary Fiction");
        }
      } catch (err) {
        console.warn(`\nOL warn: ${err.message}`);
        await sleep(1200);
      }
      page++;
      if (page % 10 === 0) writeCatalog(books, coverMap);
      await sleep(200);
    }
  }

  writeCatalog(books, coverMap);
  console.log(`Done. Catalog size: ${Math.min(books.length, TARGET_COUNT)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
