/**
 * Well-known foreign-language titles → English edition titles.
 * Used to finish anglicizing the catalog when Open Library lookups miss.
 */
export const ENGLISH_TITLE_BY_FOREIGN = {
  "Die unendliche Geschichte": "The Neverending Story",
  "Le petit prince": "The Little Prince",
  "Le Petit Prince": "The Little Prince",
  "Le avventure di Pinocchio": "The Adventures of Pinocchio",
  "Die Fließende Königin": "The Flowing Queen",
  "Die Fliessende Koenigin": "The Flowing Queen",
  "Die Stadt der Träumenden Bücher": "The City of Dreaming Books",
  "Die Stadt der Traumenden Bucher": "The City of Dreaming Books",
  "Das Labyrinth der Träumenden Bücher": "The Labyrinth of Dreaming Books",
  "Die Zwerge": "The Dwarves",
  "Das Schicksal der Zwerge": "The Fate of the Dwarves",
  "Die Elfen": "The Elves",
  "Die andere Seite": "The Other Side",
  "Broderna Lejonhjarta": "The Brothers Lionheart",
  "Bröderna Lejonhjärta": "The Brothers Lionheart",
  "Bröderna Lejonhjärta": "The Brothers Lionheart",
  "Det osynliga barnet och andra berättelser": "Tales from Moominvalley",
  "Krew elfów": "Blood of Elves",
  "Krew elfów": "Blood of Elves",
  "Wieża jaskółki": "The Tower of the Swallow",
  "Wieża jaskółki": "The Tower of the Swallow",
  "Révolte des anges": "The Revolt of the Angels",
  "Revolte des anges": "The Revolt of the Angels",
  "La casa de Riverton": "The House at Riverton",
  "Le paysan parvenu": "The Fortunate Peasant",
  "Kinder- und Hausmärchen": "Grimms' Fairy Tales",
  "Momo oder Die seltsame Geschichte von den Zeit-Dieben und von dem Kind, das den Menschen die gestohlene Zeit zurückbrachte":
    "Momo",
  "Die 13 ½ Leben des Käpt'n Blaubär": "The 13 1/2 Lives of Captain Bluebear",
  "Die 13 ½ Leben des Käpt'n Blaubär": "The 13 1/2 Lives of Captain Bluebear",
  "Séptimo viaje al reino de la fantasía": "The Seventh Adventure in the Kingdom of Fantasy",
  "Das Glasperlenspiel": "The Glass Bead Game",
  "Das Kapital": "Capital",
  "Das Parfum": "Perfume: The Story of a Murderer",
  "Das Schloß": "The Castle",
  "Das geheime Leben der Bäume": "The Hidden Life of Trees",
  "Der Steppenwolf": "Steppenwolf",
  "Der Vorleser": "The Reader",
  "Der Zauberberg": "The Magic Mountain",
  "Der Untergang des Abendlandes": "The Decline of the West",
  "Die Blechtrommel": "The Tin Drum",
  "Die Leiden des jungen Werthers": "The Sorrows of Young Werther",
  "Die Traumdeutung": "The Interpretation of Dreams",
  "Die Vermessung der Welt": "Measuring the World",
  "Die Welt als Wille und Vorstellung": "The World as Will and Representation",
  "Die Welt von Gestern": "The World of Yesterday",
  "Die Geburt der Tragödie": "The Birth of Tragedy",
  "Die Aufzeichnungen des Malte Laurids Brigge": "The Notebooks of Malte Laurids Brigge",
  "Die Känguru-Chroniken": "The Kangaroo Chronicles",
  "Die Vergewaltigung von Nanking": "The Rape of Nanking",
  "Die Wand": "The Wall",
  "Die Wolke": "The Cloud",
  "Die vierzig Tage des Musa Dagh": "The Forty Days of Musa Dagh",
  "El Aleph": "The Aleph",
  "Den femte kvinnan": "The Fifth Woman",
  "Der Antichrist": "The Antichrist",
  "Der 18. Brumaire des Louis Bonaparte": "The Eighteenth Brumaire of Louis Bonaparte",
  "Der Einzige und sein Eigentum": "The Ego and Its Own",
  "Das Drama des begabten Kindes und die Suche nach dem wahren Selbst":
    "The Drama of the Gifted Child",
  "Der Zahlenteufel": "The Number Devil",
  "Der Wolf und die sieben jungen Geisslein": "The Wolf and the Seven Young Goats",
  "Die Bremer Stadtmusikanten": "The Bremen Town Musicians",
  "Das Mädchen Anne Frank": "Anne Frank: The Diary of a Young Girl",
  "Der satanarchäolygenialkohöllische Wunschpunsch": "The Satanic Mill",
  "La Belle Sauvage": "La Belle Sauvage",
  "Un Lun Dun": "Un Lun Dun",
  "Les Misérables": "Les Misérables",
  "La planète des singes": "Planet of the Apes",
  "La Nuit des temps": "The Ice People",
  "El túnel": "The Tunnel",
  "El Club Dumas": "The Club Dumas",
  "El Juego del Ángel": "The Angel's Game",
  "La verdad sobre el caso Harry Quebert": "The Truth About the Harry Quebert Affair",
  "La vérité sur l'affaire Harry Quebert": "The Truth About the Harry Quebert Affair",
  "La forma dell'acqua": "The Shape of Water",
  "Le chien jaune": "The Yellow Dog",
  "Le Mystère de la Chambre Jaune": "The Mystery of the Yellow Room",
  "Le crime d'Orcival": "The Crime of Orcival",
  "Le dossier no. 113": "File No. 113",
  "Le Diable amoureux": "The Devil in Love",
  "Les Indes noires": "The Black Indies",
  "Le théorème du perroquet": "The Parrot's Theorem",
  "Une si longue lettre": "So Long a Letter",
  "La chica de nieve": "The Snow Girl",
  "La lluvia amarilla": "Yellow Rain",
  "El fin de Oz": "The End of Oz",
  "El reino del dragón de oro": "The Kingdom of the Golden Dragon",
  "El reino del dragón de oro": "The Kingdom of the Golden Dragon",
  "La Zizanie": "Asterix and the Roman Agent",
  "Les Guerilleres": "Les Guerilleres",
  "Der Augensammler": "The Eye Collector",
  "Die Therapie": "The Therapy",
  "Die Haarteppichknüpfer": "The Carpet Makers",
  "Die Haarteppichknüpfer": "The Carpet Makers",
  "Das Steinerne Licht": "The Stone Light",
  "Das Gläserne Wort": "The Glass Word",
  "Der Schrecksenmeister": "The Witcher Master",
  "Die Wasserweber": "The Water Weavers",
  "Die Muschelmagier": "The Shell Magicians",
  "La montagna parlante": "The Talking Mountain",
  "Un Noël De Maigret": "A Maigret Christmas",
  "La Regenta": "La Regenta",
  "La revolución vertical": "The Vertical Revolution",
  "La pell freda": "Cold Skin",
  "Los Siete Maléficos": "The Seven Evils",
  "El Gaucho": "The Gaucho",
  "Les històries naturals": "Natural Histories",
};

/** Exact-match lookup with light normalization. */
export function englishTitleOverride(title) {
  if (!title) return null;
  if (ENGLISH_TITLE_BY_FOREIGN[title]) return ENGLISH_TITLE_BY_FOREIGN[title];
  const collapsed = title.replace(/\s+/g, " ").trim();
  if (ENGLISH_TITLE_BY_FOREIGN[collapsed]) return ENGLISH_TITLE_BY_FOREIGN[collapsed];
  return null;
}
