/**
 * Expand catalog by ~10k English books (Wikidata) and anglicize remaining titles.
 * Used when openlibrary.org search is rate-limited; covers.openlibrary.org still works.
 *
 * Usage: node scripts/expandCatalogEnglish.mjs
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { englishTitleOverride } from "./englishTitleOverrides.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TARGET_COUNT = 40000;
const ADD_AT_LEAST = 10000;
const USER_AGENT = "LeafLibrary/1.0 (catalog expander; English titles)";

const NON_LATIN =
  /[\u0400-\u04FF\u0500-\u052F\u0600-\u06FF\u0900-\u097F\u3040-\u30FF\u3400-\u9FFF\uAC00-\uD7AF\u0E00-\u0E7F]/;
const FOREIGN_ARTICLES =
  /^(Die|Der|Das|Ein|Eine|El|Los|Las|Una|Unos|Unas|Le|La|Les|Un|Une|Des|Il|Lo|Gli|I|Het|Een|Den|Det|En)\s/i;

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

function normalizeTitle(title) {
  return String(title || "")
    .replace(/[\u2018\u2019\u201A\u2032]/g, "'")
    .replace(/[\u201C\u201D\u201E\u2033]/g, '"')
    .replace(/[\u2013\u2014]/g, "-")
    .replace(/\u2026/g, "...")
    .replace(/\s+/g, " ")
    .trim();
}

function looksEnglish(title) {
  const t = normalizeTitle(title);
  if (!t || NON_LATIN.test(t)) return false;
  const hasEnglishCue =
    /\b(the|a|an|of|and|or|to|in|on|for|with|from|by|at|is|are|was|were|his|her|their|my|our|you|who|what|when|where|how|book|story|life|man|woman|girl|boy|world|night|day|house|city|war|love|death|king|queen|lord|lady|dark|light|time|year|new|old|last|first|secret|great|little|black|white|red|blue|volume|vol)\b/i.test(
      t
    );
  if (FOREIGN_ARTICLES.test(t) && !hasEnglishCue) return false;
  return /[A-Za-z]{2,}/.test(t);
}

function needsEnglishLookup(title) {
  const t = normalizeTitle(title);
  if (!t) return true;
  if (NON_LATIN.test(t)) return true;
  return !looksEnglish(t);
}

function cleanIsbn13(raw) {
  const clean = String(raw || "").replace(/[^0-9Xx]/g, "");
  if (/^978\d{10}$/.test(clean) && !/^97810[0-3]/.test(clean)) return clean;
  return null;
}

function stableRating(title) {
  let hash = 0;
  for (let i = 0; i < title.length; i++) hash += title.charCodeAt(i);
  return parseFloat((3.7 + (hash % 13) / 10).toFixed(1));
}

function loadCatalog() {
  const outPath = path.resolve(__dirname, "../../frontend/src/data/mockBooksGenerated.ts");
  const raw = fs.readFileSync(outPath, "utf8");
  const match = raw.match(/export const GENERATED_BOOKS[\s\S]*?=\s*(\[)/);
  const start = match.index + match[0].length - 1;
  const end = raw.lastIndexOf("]");
  return JSON.parse(raw.slice(start, end + 1));
}

function loadCoverMap() {
  const map = {};
  try {
    const raw = fs.readFileSync(
      path.resolve(__dirname, "../../frontend/src/data/coverOverrides.ts"),
      "utf8"
    );
    for (const m of raw.matchAll(/"(\d{13})":\s*(\d+)/g)) map[m[1]] = Number(m[2]);
  } catch {
    // empty
  }
  return map;
}

function writeCatalog(books, coverMap) {
  const exact = books.slice(0, Math.max(TARGET_COUNT, books.length));
  const outPath = path.resolve(__dirname, "../../frontend/src/data/mockBooksGenerated.ts");
  const fileContent =
    `// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.\n` +
    `// Real English editions (ISBN-13). Generated ${new Date().toISOString()}\n` +
    `import { Book } from "./mockData";\n\n` +
    `export const GENERATED_BOOKS: Book[] = ${JSON.stringify(exact, null, 2)};\n`;
  fs.writeFileSync(outPath, fileContent, "utf8");

  const exactIds = new Set(exact.map((b) => b.id));
  const overridesPath = path.resolve(__dirname, "../../frontend/src/data/coverOverrides.ts");
  const entries = Object.entries(coverMap)
    .filter(([isbn]) => exactIds.has(isbn))
    .sort(([a], [b]) => a.localeCompare(b));
  fs.writeFileSync(
    overridesPath,
    `// Auto-generated Open Library cover IDs (isbn -> cover_i)\n` +
      `// Generated ${new Date().toISOString()} — real catalog only\n` +
      `export const COVER_ID_BY_ISBN: Record<string, number> = {\n` +
      entries.map(([isbn, id]) => `  "${isbn}": ${id},`).join("\n") +
      `\n};\n`,
    "utf8"
  );
  console.log(`Wrote catalog ${exact.length} books, covers ${entries.length}`);
}

async function fetchJson(url, timeoutMs = 20000) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, {
      signal: controller.signal,
      headers: { "User-Agent": USER_AGENT, Accept: "application/json" },
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return res.json();
  } finally {
    clearTimeout(timer);
  }
}

async function wikidataEnglishTitleByIsbn(isbn) {
  const hyphenated = `${isbn.slice(0, 3)}-${isbn.slice(3, 4)}-${isbn.slice(4, 9)}-${isbn.slice(9, 12)}-${isbn.slice(12)}`;
  const query = `
    SELECT ?title WHERE {
      VALUES ?isbn { "${isbn}" "${hyphenated}" }
      ?book wdt:P212 ?isbn .
      ?book rdfs:label ?title .
      FILTER(LANG(?title) = "en")
    } LIMIT 5
  `;
  const url =
    "https://query.wikidata.org/sparql?format=json&query=" + encodeURIComponent(query);
  try {
    const data = await fetchJson(url);
    for (const row of data?.results?.bindings || []) {
      const t = normalizeTitle(row.title?.value);
      if (t && looksEnglish(t)) return t;
    }
  } catch {
    return null;
  }
  return null;
}

async function anglicizeBooks(books) {
  let fixed = 0;
  let dropped = 0;
  const keep = [];

  for (let i = 0; i < books.length; i++) {
    const book = books[i];
    let title = normalizeTitle(book.title);

    const mapped = englishTitleOverride(title) || englishTitleOverride(book.title);
    if (mapped) {
      if (mapped !== book.title) fixed++;
      title = mapped;
    } else if (needsEnglishLookup(title)) {
      if (i % 25 === 0) {
        process.stdout.write(`\r  anglicize ${i + 1}/${books.length} (fixed ${fixed}, drop ${dropped})`);
      }
      const wiki = await wikidataEnglishTitleByIsbn(book.id);
      await sleep(80);
      if (wiki) {
        title = wiki;
        fixed++;
      } else if (NON_LATIN.test(title)) {
        dropped++;
        continue;
      }
    }

    keep.push({
      ...book,
      title,
      description:
        book.description?.includes(book.title) && title !== book.title
          ? `${title} by ${book.author}` + (book.year ? `, first published ${book.year}.` : ".")
          : book.description || `${title} by ${book.author}.`,
    });
  }
  console.log(`\nAnglicize done: fixed ${fixed}, dropped ${dropped}, kept ${keep.length}`);
  return keep;
}

async function fetchWikidataBatch(offset, limit) {
  // Literary works / books with ISBN-13 and English label
  const query = `
    SELECT DISTINCT ?isbn ?title ?authorLabel ?year WHERE {
      ?book wdt:P31/wdt:P279* wd:Q7725634 .
      ?book wdt:P212 ?isbn .
      ?book rdfs:label ?title .
      FILTER(LANG(?title) = "en")
      FILTER(STRSTARTS(?isbn, "978"))
      OPTIONAL {
        ?book wdt:P50 ?author .
      }
      OPTIONAL {
        ?book wdt:P577 ?date .
        BIND(YEAR(?date) AS ?year)
      }
      SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
    }
    LIMIT ${limit}
    OFFSET ${offset}
  `;
  const url =
    "https://query.wikidata.org/sparql?format=json&query=" + encodeURIComponent(query);
  const data = await fetchJson(url, 60000);
  return data?.results?.bindings || [];
}

async function expandFromWikidata(books, seen, coverMap) {
  const startCount = books.length;
  const goal = Math.max(TARGET_COUNT, startCount + ADD_AT_LEAST);
  let offset = 0;
  const pageSize = 500;

  while (books.length < goal && offset < 30000) {
    process.stdout.write(`\r[wikidata] ${books.length}/${goal} offset ${offset}…`);
    let rows = [];
    try {
      rows = await fetchWikidataBatch(offset, pageSize);
    } catch (err) {
      console.warn(`\nWikidata warn: ${err.message}`);
      await sleep(2000);
      offset += pageSize;
      continue;
    }
    if (!rows.length) break;

    for (const row of rows) {
      if (books.length >= goal) break;
      const isbn = cleanIsbn13(row.isbn?.value);
      if (!isbn || seen.has(isbn)) continue;
      const title = normalizeTitle(row.title?.value);
      if (!title || !looksEnglish(title)) continue;
      const author = normalizeTitle(row.authorLabel?.value) || "Unknown Author";
      if (author === isbn || author.startsWith("Q")) continue;
      const year = row.year?.value ? Number(row.year.value) : 2000;

      seen.add(isbn);
      books.push({
        id: isbn,
        title,
        author,
        year: Number.isFinite(year) ? year : 2000,
        description: `${title} by ${author}` + (year ? `, first published ${year}.` : "."),
        coverImage: `https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg?default=false`,
        averageRating: stableRating(title),
        genres: ["Literary Fiction", "Popular"],
        pages: 300,
      });
    }

    offset += pageSize;
    await sleep(500);

    if (books.length - startCount > 0 && (books.length - startCount) % 2000 < pageSize) {
      writeCatalog(books, coverMap);
    }
  }
  console.log(`\nWikidata added ${books.length - startCount} books`);
}

async function expandFromGutendex(books, seen, coverMap) {
  const startCount = books.length;
  const goal = Math.max(TARGET_COUNT, startCount + ADD_AT_LEAST);
  let page = 1;

  while (books.length < goal && page <= 200) {
    process.stdout.write(`\r[gutendex] ${books.length}/${goal} page ${page}…`);
    let data;
    try {
      data = await fetchJson(`https://gutendex.com/books/?languages=en&page=${page}`);
    } catch (err) {
      console.warn(`\nGutendex warn: ${err.message}`);
      break;
    }
    const results = data?.results || [];
    if (!results.length) break;

    for (const item of results) {
      if (books.length >= goal) break;
      const title = normalizeTitle(item.title);
      if (!title || !looksEnglish(title)) continue;
      const author = item.authors?.[0]?.name || "Unknown Author";
      // Gutenberg rarely has ISBN-13; synthesize stable fake-safe id from gutendex id is NOT allowed
      // Skip entries without ISBN-13 in formats/metadata
      const isbnRaw =
        item.isbns?.[0] ||
        (item.formats && Object.keys(item.formats).find(() => false)) ||
        null;
      // gutendex books payload doesn't include ISBN consistently — skip if none
      if (!isbnRaw) continue;
      const isbn = cleanIsbn13(isbnRaw);
      if (!isbn || seen.has(isbn)) continue;

      seen.add(isbn);
      books.push({
        id: isbn,
        title,
        author,
        year: 1900,
        description: `${title} by ${author}.`,
        coverImage: `https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg?default=false`,
        averageRating: stableRating(title),
        genres: ["Classics", "Literary Fiction"],
        pages: 300,
      });
    }
    if (!data.next) break;
    page++;
    await sleep(250);
  }
  console.log(`\nGutendex added ${books.length - startCount} books`);
}

/** Google Books volumes — English print books with ISBN-13. */
async function expandFromGoogleBooks(books, seen, coverMap) {
  const startCount = books.length;
  const goal = Math.max(TARGET_COUNT, startCount + ADD_AT_LEAST);
  const queries = [
    "subject:fiction",
    "subject:fantasy",
    "subject:science fiction",
    "subject:mystery",
    "subject:romance",
    "subject:history",
    "subject:biography",
    "subject:young adult",
    "subject:thriller",
    "subject:horror",
    "subject:classics",
    "subject:poetry",
    "subject:philosophy",
    "subject:business",
    "subject:psychology",
    "inauthor:king",
    "inauthor:rowling",
    "inauthor:sanderson",
    "inauthor:christie",
    "inauthor:tolkien",
    "inauthor:gaiman",
    "inauthor:atwood",
    "inauthor:murakami",
    "inauthor:stephenie meyer",
    "inauthor:james patterson",
    "inauthor:john grisham",
    "inauthor:nora roberts",
    "inauthor:agatha christie",
    "inauthor:brandon sanderson",
    "inauthor:george rr martin",
  ];

  for (const q of queries) {
    if (books.length >= goal) break;
    for (let startIndex = 0; startIndex < 120; startIndex += 40) {
      if (books.length >= goal) break;
      const url =
        `https://www.googleapis.com/books/v1/volumes?q=${encodeURIComponent(q)}` +
        `&langRestrict=en&printType=books&maxResults=40&startIndex=${startIndex}`;
      process.stdout.write(`\r[google] ${books.length}/${goal} ${q} @${startIndex}…`);
      let data;
      try {
        data = await fetchJson(url, 12000);
      } catch (err) {
        console.warn(`\nGoogle warn: ${err.message}`);
        await sleep(1500);
        break;
      }
      const items = data?.items || [];
      if (!items.length) break;

      for (const item of items) {
        if (books.length >= goal) break;
        const info = item.volumeInfo || {};
        const title = normalizeTitle(info.title);
        if (!title || !looksEnglish(title)) continue;
        const ids = info.industryIdentifiers || [];
        const isbn13 = ids.find((x) => x.type === "ISBN_13")?.identifier;
        const isbn = cleanIsbn13(isbn13);
        if (!isbn || seen.has(isbn)) continue;
        const author = info.authors?.[0] || "Unknown Author";
        const year = parseInt(String(info.publishedDate || "").slice(0, 4), 10) || 2000;
        const pages = info.pageCount || 300;
        const thumb = info.imageLinks?.thumbnail || info.imageLinks?.smallThumbnail;

        seen.add(isbn);
        books.push({
          id: isbn,
          title,
          author,
          year,
          description:
            (info.description && String(info.description).slice(0, 280)) ||
            `${title} by ${author}, first published ${year}.`,
          coverImage: thumb
            ? thumb.replace("http://", "https://")
            : `https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg?default=false`,
          averageRating:
            typeof info.averageRating === "number"
              ? parseFloat(Math.min(4.9, Math.max(3.5, info.averageRating)).toFixed(1))
              : stableRating(title),
          genres: (info.categories || ["Literary Fiction"]).slice(0, 4),
          pages,
        });
      }
      await sleep(400);
    }
    writeCatalog(books, coverMap);
  }
  console.log(`\nGoogle Books added ${books.length - startCount} books`);
}

async function main() {
  const coverMap = loadCoverMap();
  let books = loadCatalog();
  console.log(`Loaded ${books.length} books, ${Object.keys(coverMap).length} cover ids`);

  const seen = new Set(books.map((b) => b.id));

  console.log("Anglicizing titles…");
  books = await anglicizeBooks(books);
  seen.clear();
  for (const b of books) seen.add(b.id);
  writeCatalog(books, coverMap);

  const need = Math.max(0, TARGET_COUNT - books.length);
  console.log(`Need ~${Math.max(need, ADD_AT_LEAST)} more books toward ${TARGET_COUNT}`);

  await expandFromWikidata(books, seen, coverMap);
  writeCatalog(books, coverMap);

  if (books.length < TARGET_COUNT) {
    await expandFromGoogleBooks(books, seen, coverMap);
    writeCatalog(books, coverMap);
  }

  if (books.length < TARGET_COUNT) {
    await expandFromGutendex(books, seen, coverMap);
    writeCatalog(books, coverMap);
  }

  // Final English pass on any new foreign titles
  books = await anglicizeBooks(books);
  writeCatalog(books, coverMap);

  const foreignLeft = books.filter((b) => needsEnglishLookup(b.title));
  console.log(`Done. Catalog size: ${books.length}. Remaining non-English-looking: ${foreignLeft.length}`);
  if (foreignLeft.length) {
    console.log("Examples:", foreignLeft.slice(0, 10).map((b) => b.title));
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
