/**
 * Regenerate frontend/src/data/mockBooksGenerated.ts and coverOverrides.ts
 * directly from the live Supabase `books` table, so Discover shelves,
 * Lists, and anywhere else that reads the static catalog reflect every
 * book actually in the DB (including real covers).
 *
 * Usage (from backend/): node scripts/exportCatalogFromDb.mjs
 */
import { createClient } from "@supabase/supabase-js";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

let env = {};
const envPaths = [
  path.resolve(process.cwd(), ".env.local"),
  path.resolve(process.cwd(), "frontend", ".env.local"),
  path.resolve(process.cwd(), "..", "frontend", ".env.local"),
  path.resolve(process.cwd(), "backend", ".env.local"),
];
const envPath = envPaths.find((p) => fs.existsSync(p));
if (envPath) {
  fs.readFileSync(envPath, "utf8")
    .split("\n")
    .forEach((line) => {
      const m = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
      if (!m) return;
      let val = m[2] || "";
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1);
      }
      env[m[1]] = val;
    });
}

const supabaseUrl = env.NEXT_PUBLIC_SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!supabaseUrl || !supabaseKey) {
  console.error("Missing Supabase URL or service role key in .env.local");
  process.exit(1);
}
const supabase = createClient(supabaseUrl, supabaseKey);

function stableRating(title) {
  let hash = 0;
  for (let i = 0; i < title.length; i++) hash += title.charCodeAt(i);
  return parseFloat((3.6 + (hash % 13) / 10).toFixed(1));
}

function parseGenres(subjects) {
  if (!subjects) return ["Fiction"];
  try {
    const parsed = typeof subjects === "string" ? JSON.parse(subjects) : subjects;
    if (!Array.isArray(parsed) || parsed.length === 0) return ["Fiction"];
    return parsed.slice(0, 4);
  } catch {
    return ["Fiction"];
  }
}

async function fetchAllBooks() {
  const rows = [];
  const pageSize = 1000;
  let from = 0;
  for (;;) {
    const { data, error } = await supabase
      .from("books")
      .select("id, isbn_13, title, author_name, cover_url, page_count, subjects, first_publish_year, description")
      .range(from, from + pageSize - 1);
    if (error) throw error;
    if (!data || data.length === 0) break;
    rows.push(...data);
    process.stdout.write(`\rFetched ${rows.length} books…`);
    if (data.length < pageSize) break;
    from += pageSize;
  }
  console.log("");
  return rows;
}

async function main() {
  console.log("Fetching full catalog from Supabase…");
  const rows = await fetchAllBooks();
  console.log(`Fetched ${rows.length} total books from the DB.`);

  const books = [];
  const coverOverrides = {};

  for (const row of rows) {
    if (!row.id || !row.title || !row.author_name || !row.cover_url) continue;

    const genres = parseGenres(row.subjects);
    books.push({
      id: row.id,
      title: row.title,
      author: row.author_name,
      year: row.first_publish_year || 2000,
      description: row.description || `${row.title} by ${row.author_name}.`,
      coverImage: row.cover_url,
      averageRating: stableRating(row.title),
      genres,
      pages: row.page_count || 300,
    });

    if (row.isbn_13) {
      const m = row.cover_url.match(/\/b\/id\/(\d+)-/);
      if (m) coverOverrides[row.isbn_13] = Number(m[1]);
    }
  }

  console.log(`Writing ${books.length} books with real covers…`);

  const catalogPath = path.resolve(__dirname, "../../frontend/src/data/mockBooksGenerated.ts");
  const catalogContent =
    `// THIS FILE IS AUTOMATICALLY GENERATED FROM THE LIVE SUPABASE \`books\` TABLE. DO NOT EDIT.\n` +
    `// Regenerate with: node backend/scripts/exportCatalogFromDb.mjs\n` +
    `// Generated ${new Date().toISOString()}\n` +
    `import { Book } from "./mockData";\n\n` +
    `export const GENERATED_BOOKS: Book[] = ${JSON.stringify(books, null, 2)};\n`;
  fs.writeFileSync(catalogPath, catalogContent, "utf8");
  console.log(`Wrote ${catalogPath}`);

  const overridesPath = path.resolve(__dirname, "../../frontend/src/data/coverOverrides.ts");
  const entries = Object.entries(coverOverrides).sort(([a], [b]) => a.localeCompare(b));
  const overridesContent =
    `// Auto-generated Open Library cover IDs (isbn -> cover_i)\n` +
    `// Regenerate with: node backend/scripts/exportCatalogFromDb.mjs\n` +
    `// Generated ${new Date().toISOString()} — mirrors the live \`books\` table\n` +
    `export const COVER_ID_BY_ISBN: Record<string, number> = {\n` +
    entries.map(([isbn, id]) => `  "${isbn}": ${id},`).join("\n") +
    `\n};\n`;
  fs.writeFileSync(overridesPath, overridesContent, "utf8");
  console.log(`Wrote ${overridesPath} (${entries.length} covers)`);
}

main().catch((err) => {
  console.error("\nFatal error:", err);
  process.exit(1);
});
