/**
 * Fill COVER_ID_BY_ISBN for every catalog book by probing the Open Library
 * covers CDN (ISBN → redirect to archive cover file whose name embeds cover_i).
 * Books without a resolvable cover_i get an /api/covers proxy URL (Google fallback).
 *
 * Usage: node scripts/fillAllCovers.mjs
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const USER_AGENT = "LeafLibrary/1.0 (fill missing covers via CDN)";
const CONCURRENCY = 28;
const CHECKPOINT_EVERY = 1000;
const CDN_RETRIES = 2;

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

function loadBooks() {
  const outPath = path.resolve(__dirname, "../../frontend/src/data/mockBooksGenerated.ts");
  const raw = fs.readFileSync(outPath, "utf8");
  const match = raw.match(/export const GENERATED_BOOKS[\s\S]*?=\s*(\[)/);
  const start = match.index + match[0].length - 1;
  const end = raw.lastIndexOf("]");
  return { books: JSON.parse(raw.slice(start, end + 1)), outPath };
}

function loadCoverMap() {
  const map = {};
  const overridesPath = path.resolve(__dirname, "../../frontend/src/data/coverOverrides.ts");
  try {
    const raw = fs.readFileSync(overridesPath, "utf8");
    for (const m of raw.matchAll(/"(\d{13})":\s*(\d+)/g)) map[m[1]] = Number(m[2]);
  } catch {
    // empty
  }
  return { map, overridesPath };
}

function writeOutputs(books, coverMap, booksPath, overridesPath) {
  fs.writeFileSync(
    booksPath,
    `// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.\n` +
      `// Real editions (ISBN-13 + cover). Generated ${new Date().toISOString()}\n` +
      `import { Book } from "./mockData";\n\n` +
      `export const GENERATED_BOOKS: Book[] = ${JSON.stringify(books, null, 2)};\n`,
    "utf8"
  );
  const entries = Object.entries(coverMap).sort(([a], [b]) => a.localeCompare(b));
  fs.writeFileSync(
    overridesPath,
    `// Auto-generated Open Library cover IDs (isbn -> cover_i)\n` +
      `// Generated ${new Date().toISOString()}\n` +
      `export const COVER_ID_BY_ISBN: Record<string, number> = {\n` +
      entries.map(([isbn, id]) => `  "${isbn}": ${id},`).join("\n") +
      `\n};\n`,
    "utf8"
  );
}

function extractCoverId(url) {
  if (!url) return null;
  const idMatch = String(url).match(/[?&]id=(\d+)/) || String(url).match(/\/b\/id\/(\d+)/);
  return idMatch ? Number(idMatch[1]) : null;
}

function proxyCoverUrl(book) {
  const params = new URLSearchParams({ isbn: book.id, size: "L" });
  if (book.title) params.set("title", book.title);
  if (book.author) params.set("author", book.author);
  return `/api/covers?${params.toString()}`;
}

/** HEAD isbn cover URL without following redirects; parse cover_i from Location. */
async function resolveCoverFromCdn(isbn) {
  for (let attempt = 0; attempt < CDN_RETRIES; attempt++) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 7000);
    try {
      const res = await fetch(
        `https://covers.openlibrary.org/b/isbn/${isbn}-M.jpg?default=false`,
        {
          method: "HEAD",
          redirect: "manual",
          signal: controller.signal,
          headers: { "User-Agent": USER_AGENT },
        }
      );

      if (res.status >= 300 && res.status < 400) {
        const loc = res.headers.get("location") || "";
        const fromArchive = loc.match(/\/(\d{7,})-[SML]\.jpg/i);
        if (fromArchive) {
          const id = Number(fromArchive[1].replace(/^0+/, "") || "0");
          if (id > 0) return id;
        }
        const fromOl = loc.match(/\/b\/id\/(\d+)/);
        if (fromOl) return Number(fromOl[1]);
        return { okNoId: true };
      }

      if (res.ok) return { okNoId: true };
      if (res.status === 404) return null;
    } catch {
      // retry
    } finally {
      clearTimeout(timer);
    }
    await sleep(120 * (attempt + 1));
  }
  return null;
}

async function runPool(items, worker, concurrency) {
  let idx = 0;
  let active = 0;
  return new Promise((resolve) => {
    const next = () => {
      if (idx >= items.length && active === 0) return resolve();
      while (active < concurrency && idx < items.length) {
        const item = items[idx++];
        active++;
        worker(item)
          .catch(() => {})
          .finally(() => {
            active--;
            next();
          });
      }
    };
    next();
  });
}

async function main() {
  const { books, outPath: booksPath } = loadBooks();
  const { map: coverMap, overridesPath } = loadCoverMap();

  let synced = 0;
  for (const book of books) {
    const fromUrl = extractCoverId(book.coverImage);
    if (fromUrl && !coverMap[book.id]) {
      coverMap[book.id] = fromUrl;
      synced++;
    }
  }
  console.log(`Synced ${synced} cover IDs from coverImage URLs`);
  console.log(`Cover map: ${Object.keys(coverMap).length}/${books.length}`);

  const missing = books.filter((b) => !coverMap[b.id]);
  console.log(`CDN-resolving ${missing.length} missing covers…`);

  let fixed = 0;
  let isbnOnly = 0;
  let proxyOnly = 0;
  let processed = 0;

  await runPool(
    missing,
    async (book) => {
      const result = await resolveCoverFromCdn(book.id);
      processed++;

      if (typeof result === "number" && result > 0) {
        coverMap[book.id] = result;
        book.coverImage = `https://covers.openlibrary.org/b/id/${result}-L.jpg?default=false`;
        fixed++;
      } else if (result && result.okNoId) {
        book.coverImage = proxyCoverUrl(book);
        isbnOnly++;
      } else {
        book.coverImage = proxyCoverUrl(book);
        proxyOnly++;
      }

      if (processed % 100 === 0 || processed === missing.length) {
        process.stdout.write(
          `\r  ${processed}/${missing.length}  id=${fixed} isbn=${isbnOnly} proxy=${proxyOnly}`
        );
      }
      if (processed % CHECKPOINT_EVERY === 0) {
        writeOutputs(books, coverMap, booksPath, overridesPath);
        process.stdout.write(`\nCheckpoint covers=${Object.keys(coverMap).length}\n`);
        await sleep(150);
      }
    },
    CONCURRENCY
  );

  for (const book of books) {
    if (coverMap[book.id]) {
      book.coverImage = `https://covers.openlibrary.org/b/id/${coverMap[book.id]}-L.jpg?default=false`;
    } else if (!book.coverImage || !String(book.coverImage).trim()) {
      book.coverImage = proxyCoverUrl(book);
    }
  }

  writeOutputs(books, coverMap, booksPath, overridesPath);
  console.log(`\nWrote catalog + overrides (${Object.keys(coverMap).length} cover_i mappings)`);
  console.log(
    `Summary: cover_i=${Object.keys(coverMap).length}/${books.length}, isbn-cdn=${isbnOnly}, proxy-fallback=${proxyOnly}`
  );

  const uncovered = books.filter((b) => !coverMap[b.id] && !(b.coverImage && String(b.coverImage).trim()));
  if (uncovered.length) {
    console.log(`WARNING: ${uncovered.length} books still lack any cover URL`);
  } else {
    console.log("All books have a cover URL (cover_i and/or /api/covers).");
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
