/**
 * Finish expansion to 40k + apply English title overrides (local + Wikidata).
 * Usage: node scripts/finishCatalogExpand.mjs
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { englishTitleOverride } from "./englishTitleOverrides.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TARGET = 40000;
const USER_AGENT = "LeafLibrary/1.0 (catalog finish; English titles)";

const NON_LATIN =
  /[\u0400-\u04FF\u0500-\u052F\u0600-\u06FF\u0900-\u097F\u3040-\u30FF\u3400-\u9FFF\uAC00-\uD7AF]/;

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

function normalizeTitle(title) {
  return String(title || "")
    .replace(/[\u2018\u2019\u201A\u2032]/g, "'")
    .replace(/[\u201C\u201D\u201E\u2033]/g, '"')
    .replace(/[\u2013\u2014]/g, "-")
    .replace(/\u2026/g, "...")
    .replace(/\s+/g, " ")
    .trim();
}

function looksEnglish(title) {
  const t = normalizeTitle(title);
  if (!t || NON_LATIN.test(t)) return false;
  // "Die Softly" / "Die Trying" are English
  if (/^Die (Softly|Trying|Hard|Young|Another Day)\b/i.test(t)) return true;
  const hasEnglishCue =
    /\b(the|a|an|of|and|or|to|in|on|for|with|from|by|at|book|story|life|man|woman|girl|boy|world|night|day|house|city|war|love|death|king|queen|lord|lady|dark|light|time|year|new|old|last|first|secret|great|little|black|white|red|blue|volume|vol)\b/i.test(
      t
    );
  if (/^(Die|Der|Das|El|Los|Las|Le|La|Les|Un|Une)\s/.test(t) && !hasEnglishCue) return false;
  return /[A-Za-z]{2,}/.test(t);
}

function cleanIsbn13(raw) {
  const clean = String(raw || "").replace(/[^0-9Xx]/g, "");
  if (/^978\d{10}$/.test(clean) && !/^97810[0-3]/.test(clean)) return clean;
  return null;
}

function stableRating(title) {
  let hash = 0;
  for (let i = 0; i < title.length; i++) hash += title.charCodeAt(i);
  return parseFloat((3.7 + (hash % 13) / 10).toFixed(1));
}

function loadCatalog() {
  const outPath = path.resolve(__dirname, "../../frontend/src/data/mockBooksGenerated.ts");
  const raw = fs.readFileSync(outPath, "utf8");
  const match = raw.match(/export const GENERATED_BOOKS[\s\S]*?=\s*(\[)/);
  const start = match.index + match[0].length - 1;
  const end = raw.lastIndexOf("]");
  return JSON.parse(raw.slice(start, end + 1));
}

function loadCoverMap() {
  const map = {};
  const raw = fs.readFileSync(path.resolve(__dirname, "../../frontend/src/data/coverOverrides.ts"), "utf8");
  for (const m of raw.matchAll(/"(\d{13})":\s*(\d+)/g)) map[m[1]] = Number(m[2]);
  return map;
}

function writeCatalog(books, coverMap) {
  const exact = books.slice(0, Math.max(TARGET, books.length));
  const outPath = path.resolve(__dirname, "../../frontend/src/data/mockBooksGenerated.ts");
  fs.writeFileSync(
    outPath,
    `// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.\n` +
      `// Real English editions (ISBN-13). Generated ${new Date().toISOString()}\n` +
      `import { Book } from "./mockData";\n\n` +
      `export const GENERATED_BOOKS: Book[] = ${JSON.stringify(exact, null, 2)};\n`,
    "utf8"
  );
  const ids = new Set(exact.map((b) => b.id));
  const entries = Object.entries(coverMap)
    .filter(([isbn]) => ids.has(isbn))
    .sort(([a], [b]) => a.localeCompare(b));
  fs.writeFileSync(
    path.resolve(__dirname, "../../frontend/src/data/coverOverrides.ts"),
    `// Auto-generated Open Library cover IDs (isbn -> cover_i)\n` +
      `// Generated ${new Date().toISOString()} — real catalog only\n` +
      `export const COVER_ID_BY_ISBN: Record<string, number> = {\n` +
      entries.map(([isbn, id]) => `  "${isbn}": ${id},`).join("\n") +
      `\n};\n`,
    "utf8"
  );
  console.log(`Wrote ${exact.length} books, ${entries.length} covers`);
}

async function fetchJson(url, timeoutMs = 15000) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, {
      signal: controller.signal,
      headers: { "User-Agent": USER_AGENT, Accept: "application/json" },
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    return res.json();
  } finally {
    clearTimeout(timer);
  }
}

async function wikiEnglish(isbn) {
  const query = `
    SELECT ?title WHERE {
      ?book wdt:P212 "${isbn}" .
      ?book rdfs:label ?title .
      FILTER(LANG(?title) = "en")
    } LIMIT 3`;
  try {
    const data = await fetchJson(
      "https://query.wikidata.org/sparql?format=json&query=" + encodeURIComponent(query)
    );
    for (const row of data?.results?.bindings || []) {
      const t = normalizeTitle(row.title?.value);
      if (t && looksEnglish(t)) return t;
    }
  } catch {
    return null;
  }
  return null;
}

async function main() {
  const coverMap = loadCoverMap();
  let books = loadCatalog();
  console.log(`Loaded ${books.length}`);

  // 1) Local static overrides + normalize
  let fixed = 0;
  const kept = [];
  for (const book of books) {
    let title = normalizeTitle(book.title);
    const mapped = englishTitleOverride(title) || englishTitleOverride(book.title);
    if (mapped) {
      if (mapped !== book.title) fixed++;
      title = mapped;
    }
    kept.push({
      ...book,
      title,
      description:
        title !== book.title
          ? `${title} by ${book.author}` + (book.year ? `, first published ${book.year}.` : ".")
          : book.description,
    });
  }
  books = kept;
  console.log(`Static overrides applied: ${fixed}`);

  // 2) Wikidata for remaining foreign-looking (batched lightly)
  const suspects = books.filter((b) => !looksEnglish(b.title));
  console.log(`Wikidata lookup for ${suspects.length} remaining…`);
  let wikiFixed = 0;
  const drop = new Set();
  for (let i = 0; i < suspects.length; i++) {
    const book = suspects[i];
    process.stdout.write(`\r  wiki ${i + 1}/${suspects.length} (fixed ${wikiFixed})`);
    const eng = await wikiEnglish(book.id);
    await sleep(100);
    if (eng) {
      book.title = eng;
      book.description = `${eng} by ${book.author}` + (book.year ? `, first published ${book.year}.` : ".");
      wikiFixed++;
    } else if (NON_LATIN.test(book.title)) {
      drop.add(book.id);
    }
  }
  console.log(`\nWiki fixed ${wikiFixed}, drop ${drop.size}`);
  books = books.filter((b) => !drop.has(b.id));
  writeCatalog(books, coverMap);

  // 3) Google Books fill to TARGET
  const seen = new Set(books.map((b) => b.id));
  const queries = [
    "subject:fiction",
    "subject:fantasy",
    "subject:science fiction",
    "subject:mystery",
    "subject:romance",
    "subject:biography",
    "subject:history",
    "subject:young adult fiction",
    "subject:thriller",
    "subject:horror",
    "subject:literary fiction",
    "subject:historical fiction",
    "subject:contemporary fiction",
    "subject:adventure stories",
    "subject:detective",
    "inauthor:jane austen",
    "inauthor:charles dickens",
    "inauthor:ernest hemingway",
    "inauthor:virginia woolf",
    "inauthor:toni morrison",
    "inauthor:margaret atwood",
    "inauthor:neil gaiman",
    "inauthor:terry pratchett",
    "inauthor:ursula k le guin",
    "inauthor:octavia butler",
    "inauthor:philip k dick",
    "inauthor:isaac asimov",
    "inauthor:agatha christie",
    "inauthor:arthur conan doyle",
    "inauthor:stephen king",
  ];

  for (const q of queries) {
    if (books.length >= TARGET) break;
    for (let startIndex = 0; startIndex < 160; startIndex += 40) {
      if (books.length >= TARGET) break;
      const url =
        `https://www.googleapis.com/books/v1/volumes?q=${encodeURIComponent(q)}` +
        `&langRestrict=en&printType=books&maxResults=40&startIndex=${startIndex}`;
      process.stdout.write(`\r[google] ${books.length}/${TARGET} ${q} @${startIndex}   `);
      let data;
      try {
        data = await fetchJson(url);
      } catch (err) {
        console.warn(`\nGoogle: ${err.message}`);
        await sleep(2000);
        break;
      }
      const items = data?.items || [];
      if (!items.length) break;
      for (const item of items) {
        if (books.length >= TARGET) break;
        const info = item.volumeInfo || {};
        const title = normalizeTitle(info.title);
        if (!title || !looksEnglish(title)) continue;
        const isbn = cleanIsbn13(
          (info.industryIdentifiers || []).find((x) => x.type === "ISBN_13")?.identifier
        );
        if (!isbn || seen.has(isbn)) continue;
        seen.add(isbn);
        const author = info.authors?.[0] || "Unknown Author";
        const year = parseInt(String(info.publishedDate || "").slice(0, 4), 10) || 2000;
        const thumb = info.imageLinks?.thumbnail || info.imageLinks?.smallThumbnail;
        books.push({
          id: isbn,
          title,
          author,
          year,
          description:
            (info.description && String(info.description).slice(0, 280)) ||
            `${title} by ${author}, first published ${year}.`,
          coverImage: thumb
            ? thumb.replace("http://", "https://")
            : `https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg?default=false`,
          averageRating:
            typeof info.averageRating === "number"
              ? parseFloat(Math.min(4.9, Math.max(3.5, info.averageRating)).toFixed(1))
              : stableRating(title),
          genres: (info.categories || ["Literary Fiction"]).slice(0, 4),
          pages: info.pageCount || 300,
        });
      }
      await sleep(350);
    }
    writeCatalog(books, coverMap);
  }

  const foreign = books.filter((b) => !looksEnglish(b.title));
  console.log(`\nDone. ${books.length} books. Non-English-looking left: ${foreign.length}`);
  if (foreign.length) console.log(foreign.slice(0, 15).map((b) => b.title));
  writeCatalog(books, coverMap);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
